notify 100 {
    match "system"      "VFS";
    match "subsystem"   "FS";
    match "type"        "MOUNT|REMOUNT";
    match "mount-type"  "msdosfs";
    action "/usr/local/bin/usb-notify.sh attach $mount-dev &";
};

notify 100 {
    match "system"      "VFS";
    match "subsystem"   "FS";
    match "type"        "UNMOUNT";
    match "mount-type"  "msdosfs";
    action "/usr/local/bin/usb-notify.sh detach $mount-dev &";
};