notify 100 {
    match "system" "DEVFS";
    match "type"   "CREATE";
    match "cdev"   "da[0-9]+s[0-9]+";
    action "/usr/local/bin/usb-notify.sh attach $cdev &";
};

notify 100 {
    match "system" "DEVFS";
    match "type"   "DESTROY";
    match "cdev"   "da[0-9]+s[0-9]+";
    action "/usr/local/bin/usb-notify.sh detach $cdev &";
};