## Desktop rules
table <bruteforce> persist

# ICMP
pass in inet proto icmp icmp-type { echoreq, unreach, timex } keep state
pass in inet6 proto icmp6 all keep state

# LAN unrestricted (notebook + router)
pass in quick on $ext_if from 192.168.0.0/24 to any keep state

# SSH with brute force protection
pass in proto tcp from any to any port ssh \
    flags S/SA keep state \
    (max-src-conn 5, max-src-conn-rate 3/10, overload <bruteforce> flush global)
block quick from <bruteforce>