clear_tmp_enable="YES"
hostname="freebsd"
keymap="latinamerican.acc.kbd"
ifconfig_re0="DHCP"
ifconfig_re0_ipv6="inet6 accept_rtadv"
sshd_enable="YES"
moused_nondefault_enable="NO"
# Set dumpdev to "AUTO" to enable crash dumps, "NO" to disable
dumpdev="AUTO"
zfs_enable="YES"
linux_enable="YES"
kld_list="nvidia-modeset nvidia-drm fusefs"
seatd_enable="YES"
dbus_enable="YES"
xdg_runtime_enable="YES"
ntpd_enable="YES"
ntpd_flags="-g"
autofs_enable="YES"
bastille_enable="YES"
cloned_interfaces="lo1"
ifconfig_lo1_name="bastille0"
pf_enable="YES"
