#!/bin/sh

COLORS="-b \
    --fn 'Luxi Sans 11' \
    --hp 15 \
    --line-height 20 \
    --tb '#333333' --tf '#eeeeee' \
    --fb '#bbbbbb' --ff '#222222' \
    --cb '#bbbbbb' --cf '#222222' \
    --nb '#bbbbbb' --nf '#222222' \
    --hb '#333333' --hf '#eeeeee' \
    --sb '#333333' --sf '#eeeeee' \
    --ab '#bbbbbb' --af '#222222' \
    --fbb '#bbbbbb' --fbf '#222222' \
    --scb '#999999' --scf '#111111' \
    --bdr '#222222'"

case "$(basename $0)" in
    bemenu-run-themed) eval exec bemenu-run $COLORS "$@" ;;
    *)                 eval exec bemenu $COLORS "$@" ;;
esac