[/]
custom-keybindings=['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']
next=['<Shift><Super>d']
play=['<Shift><Super>s']
previous=['<Shift><Super>a']
screensaver=@as []

[custom-keybindings/custom0]
binding='<Shift><Super>e'
command='nautilus'
name='Open file explorer'
