[/]
custom-keybindings=['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']
next=['<Super>d']
play=['<Super>s']
previous=['<Super>a']

[custom-keybindings/custom0]
binding='<Super>e'
command='nautilus'
name='Open file explorer'
