[/]
custom-keybindings=['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']
next=['<Control><Alt>l']
pause=['<Control><Alt>j']
play=['<Control><Alt>k']
previous=['<Control><Alt>h']

[custom-keybindings/custom0]
binding='<Super>e'
command='nautilus'
name='Open file explorer'
