#!/bin/sh

export XDG_SESSION_TYPE=wayland
export XDG_CURRENT_DESKTOP=dwl
export XCURSOR_THEME=TempleOS_Cursor
export XCURSOR_SIZE=32
dbus-update-activation-environment --systemd XCURSOR_SIZE=32 XCURSOR_THEME=TempleOS_Cursor
env >> /tmp/dwl-session-env.log
exec dwl -s /home/mnlcz/Projects/config/wm/dwl/dwl-startup
