#!/bin/sh
echo "LAT" > /tmp/dwl-layout
mako &
wl-paste --watch cliphist store &
wl-paste --watch xsel --primary --input &
swaybg -i /home/mnlcz/Pictures/templeos.jpeg -m fill &
sleep 3
/home/mnlcz/Projects/config/wm/dwl/dwlb/status.sh &
dwlb
