#!/bin/sh
echo "LATAM" > /tmp/dwl-layout
export XCURSOR_THEME=TempleOS_Simple
export XCURSOR_SIZE=32
mako &
wl-paste --watch cliphist store &
wl-paste --watch xsel --primary --input &
swaybg -i /usr/share/backgrounds/rhel10-3D-l.png -m fill &
sleep 3
/home/mnlcz/Projects/config/wm/dwl/dwlb/status.sh &
dwlb
